apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-depl
spec:
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
        - name: address
          image: sluis117/address
          env:
            - name: MONGO_URL
              value: 'mongodb://address-mongo-srv:27017/address'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shopGt
---
apiVersion: v1
kind: Service
metadata:
  name: address-srv
spec:
  selector:
    app: address
  ports:
    - name: address
      protocol: TCP
      port: 3000
      targetPort: 3000
