apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: sluis117/product
          env:
            - name: MONGO_URL
              value: 'mongodb://product-mongo-srv:27017/product'
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: ACCESS_KEY_ID
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: SECRET_ACCESS_KEY
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: BUCKET_NAME
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000
