apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopcart-depl
spec:
  selector:
    matchLabels:
      app: shopcart
  template:
    metadata:
      labels:
        app: shopcart
    spec:
      containers:
        - name: shopcart
          image: sluis117/shopcart
          env:
            - name: MONGO_URL
              value: 'mongodb://shopcart-mongo-srv:27017/shopcart'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shopGt
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: shopcart-srv
spec:
  selector:
    app: shopcart
  ports:
    - name: shopcart
      protocol: TCP
      port: 3000
      targetPort: 3000
